src/main/java/com/zblog/core/dal/entity/Comment.java
package com.zblog.core.dal.entity;

import com.zblog.core.dal.constants.CommentConstants;

public class Comment extends BaseEntity{
  private String postid;
  /* 评论者邮箱 */
  private String email;
  /* 评论者网址 */
  private String url;
  /* 评论者IP */
  private String ip;
  /* 内容 */
  private String content;
  /* 评论状态 */
  private String status = CommentConstants.TYPE_WAIT;
  /* 评论者的userAgent */
  private String agent;
  /* 父评论ID */
  private String parent;

  public String getPostid(){
    return postid;
  }

  public void setPostid(String postid){
    this.postid = postid;
  }

  public String getEmail(){
    return email;
  }

  public void setEmail(String email){
    this.email = email;
  }

  public String getUrl(){
    return url;
  }

  public void setUrl(String url){
    this.url = url;
  }

  public String getIp(){
    return ip;
  }

  public void setIp(String ip){
    this.ip = ip;
  }

  public String getContent(){
    return content;
  }

  public void setContent(String content){
    this.content = content;
  }

  public boolean isApproved(){
    return status.equals(CommentConstants.TYPE_APPROVE);
  }

  public String getStatus(){
    return status;
  }

  public void setStatus(String status){
    this.status = status;
  }

  public String getAgent(){
    return agent;
  }

  public void setAgent(String agent){
    this.agent = agent;
  }

  public String getParent(){
    return parent;
  }

  public void setParent(String parent){
    this.parent = parent;
  }

}

src/main/java/com/zblog/service/vo/Global.java
package com.zblog.service.vo;

import java.util.Calendar;
import java.util.Date;

import com.zblog.core.dal.constants.OptionConstants;
import com.zblog.core.plugin.ApplicationContextUtil;
import com.zblog.service.OptionsService;

/**
 * view中使用的的对象
 * 
 * @author zhou
 *
 */
public class Global{
  private String domain;

  public Global(String domain){
    this.domain = domain;
  }

  public String getTitle(){
    return getOptionValue(OptionConstants.TITLE);
  }

  public String getSubtitle(){
    return getOptionValue(OptionConstants.SUBTITLE);
  }

  public String getDescription(){
    return getOptionValue(OptionConstants.DESCRIPTION);
  }
  
  public String getKeywords(){
    return getOptionValue(OptionConstants.KEYWORDS);
  }

  public boolean isAllowComment(){
    return Boolean.parseBoolean(getOptionValue(OptionConstants.ALLOW_COMMENT));
  }

  public int getYear(){
    Calendar calendar = Calendar.getInstance();
    calendar.setTime(new Date());
    return calendar.get(Calendar.YEAR);
  }

  public String getDomain(){
    return domain;
  }

  private static String getOptionValue(String name){
    OptionsService optionsService = ApplicationContextUtil.getBean(OptionsService.class);
    return optionsService.getOptionValue(name);
  }

}

src/main/java/com/zblog/web/backend/controller/CommentController.java
package com.zblog.web.backend.controller;

import java.util.Arrays;
import java.util.Collection;

import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zblog.biz.CommentManager;
import com.zblog.core.dal.constants.CommentConstants;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.plugin.PageModel;
import com.zblog.service.CommentService;

@Controller("adminCommentController")
@RequestMapping("/backend/comments")
@RequiresRoles("admin")
public class CommentController{
  @Autowired
  private CommentService commentService;
  @Autowired
  private CommentManager commentManager;

  @RequestMapping(method = RequestMethod.GET)
  public String index(@RequestParam(value = "page", defaultValue = "1") int page,
      @RequestParam(value = "type", defaultValue = "all") String type, Model model){
    Collection<String> status = "all".equals(type) ? Arrays.asList(CommentConstants.TYPE_APPROVE,
        CommentConstants.TYPE_WAIT) : Arrays.asList(type);
    PageModel<MapContainer> pageModel = commentService.listByStatus(page, 15, status);
    model.addAttribute("page", pageModel);
    model.addAttribute("type", type);
    model.addAttribute("stat", commentService.listCountByGroupStatus());
    return "backend/comment/list";
  }

  @ResponseBody
  @RequestMapping(value = "/{commentid}", method = RequestMethod.DELETE)
  public Object remove(@PathVariable("commentid") String commentid){
    commentManager.deleteComment(commentid);
    return new MapContainer("success", true);
  }

  /**
   * 修改评论状态
   * 
   * @param commentid
   * @param status
   * @return
   */
  @ResponseBody
  @RequestMapping(value = "/{commentid}", method = RequestMethod.PUT)
  public Object approve(@PathVariable("commentid") String commentid, String status){
    commentManager.setStatus(commentid, status);
    return new MapContainer("success", true);
  }

}

src/main/java/com/zblog/web/front/controller/CommentController.java
package com.zblog.web.front.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.util.HtmlUtils;

import com.zblog.core.dal.constants.OptionConstants;
import com.zblog.core.dal.constants.PostConstants;
import com.zblog.core.dal.entity.Comment;
import com.zblog.core.dal.entity.Post;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.util.CookieUtil;
import com.zblog.core.util.IdGenerator;
import com.zblog.core.util.JsoupUtils;
import com.zblog.core.util.ServletUtils;
import com.zblog.core.util.StringUtils;
import com.zblog.service.CommentService;
import com.zblog.service.OptionsService;
import com.zblog.service.PostService;
import com.zblog.web.front.validator.CommentValidator;

@Controller
@RequestMapping("/comments")
public class CommentController{
  @Autowired
  private CommentService commentService;
  @Autowired
  private PostService postService;
  @Autowired
  private OptionsService optionsService;

  @ResponseBody
  @RequestMapping(method = RequestMethod.POST)
  public Object post(Comment comment, HttpServletRequest request, HttpServletResponse response){
    CookieUtil cookieUtil = new CookieUtil(request, response);
    if(StringUtils.isBlank(comment.getCreator())){
      comment.setCreator(cookieUtil.getCookie("comment_author"));
      comment.setUrl(cookieUtil.getCookie("comment_author_url", false));
      comment.setEmail(cookieUtil.getCookie("comment_author_email", false));
    }

    MapContainer form = CommentValidator.validate(comment);
    if(!form.isEmpty()){
      return form.put("success", false);
    }

    if(!"true".equals(optionsService.getOptionValue(OptionConstants.ALLOW_COMMENT)))
      return new MapContainer("success", false).put("msg", "当前禁止评论");

    Post post = postService.loadById(comment.getPostid());
    if(post == null || PostConstants.COMMENT_CLOSE.equals(post.getCstatus())){
      return new MapContainer("success", false).put("msg", "当前禁止评论");
    }

    if(StringUtils.isBlank(comment.getParent())){
      comment.setParent(null);
    }

    /* 根据RFC-2109中的规定，在Cookie中只能包含ASCII的编码 */
    cookieUtil.setCookie("comment_author", comment.getCreator(), "/", false, 365 * 24 * 3600, true);
    cookieUtil.setCookie("comment_author_email", comment.getEmail(), "/", false, 365 * 24 * 3600, false);
    cookieUtil.setCookie("comment_author_url", comment.getUrl(), "/", false, 365 * 24 * 3600, false);

    comment.setId(IdGenerator.uuid19());
    comment.setIp(ServletUtils.getIp(request));
    comment.setAgent(request.getHeader("User-Agent"));
    comment.setCreateTime(new Date());
    comment.setLastUpdate(comment.getCreateTime());
    /* 使用jsoup来对帖子内容进行过滤 */
    String content = HtmlUtils.htmlUnescape(comment.getContent());
    comment.setContent(JsoupUtils.simpleText(content));
    commentService.insert(comment);
    return new MapContainer("success", true);
  }

}

src/main/webapp/WEB-INF/jsp/common/comments_form.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="z" uri="/WEB-INF/tld/function.tld" %>
<%@ taglib uri="/WEB-INF/tld/shiro-function.tld" prefix="sf" %>
<fieldset id="respond" class="comment_form_wrapper">
<c:choose>
 <c:when test="${!g.allowComment || post.cstatus=='close'|| (!sf:isUser()&&post.pstatus=='secret')}">
  当前禁止评论
 </c:when>
 <c:otherwise>
  <div id="cancel_comment_reply">
     <a href="#respond" rel="nofollow">点击这里取消回复。</a>
  </div>
 <!--  <form method="post" action="/comments" id="comment_form"> -->
    <input type="hidden" id="postid" name="postid" value="${post.id}" />
    <input type="hidden" id="comment_parent" name="parent" />
    <c:if test="${cookie.comment_author!=null}">
      <div id="guest_info">登录身份:${z:cookieValue('comment_author')}</div>
    </c:if>
    <c:if test="${cookie.comment_author==null}">
     <div id="guest_info">
      <div id="guest_name">
       <label for="author"><span>昵称</span>( 必须 )</label>
       <input id="author" autocomplete="off" type="text" aria-required="true" size="22" name="creator">
      </div>
      <div id="guest_email">
        <label for="email"><span>E-MAIL</span>( 必须 ) - 不会公开 -</label>
        <input id="email" autocomplete="off" type="text" aria-required="true" size="22" name="email">
      </div>
      <div id="guest_url">
        <label for="url"><span>网址</span></label>
        <input id="url" type="text" tabindex="3" size="22" placeholder="http://" name="url">
      </div>
     </div>
    </c:if>
    <div id="comment_textarea">
      <textarea id="comment" tabindex="4" rows="10" cols="50" name="content"></textarea>
    </div>
    <div id="submit_comment_wrapper">
      <input id="submit_comment" type="button" value="发表评论" >
    </div>
<!--   </form> -->
 </c:otherwise>
</c:choose>
</fieldset>
<script src="${g.domain}/resource/js/zblog.js"></script>

src/main/webapp/WEB-INF/jsp/common/comments_list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<ol class="commentlist">
  <c:forEach items="${comments}" var="comment" varStatus="status">
   <c:choose>
    <c:when test="${depth==null||depth==0}">
     <li class="comment ${status.index%2==0?'even_comment':'odd_comment'}" id="comment-${comment.id}">
    </c:when>
    <c:otherwise>
      <li class="comment ${depth%2==(parent?0:1)?'even_comment':'odd_comment'}" id="comment-${comment.id}">
    </c:otherwise>
   </c:choose>
   <div class="comment-meta">
     <img class="avatar" width="35" height="35" src="../../resource/img/avatar.png" />
     <ul class="comment-name-date">
       <li class="comment-name"><a class="url" target="_blank" href="${comment.url}">${comment.creator}</a></li>
       <li class="comment-date"><fmt:formatDate value="${comment.createTime}" pattern="yyyy/MM/dd hh:mma"/></li>
      </ul>
      <c:if test="${comment.status=='approve'}"><div class="comment-reply"><a href='#respond'>回复</a></div></c:if>
     </div>
     <div class="comment-content">
       <c:if test="${comment.status=='wait'}">
        <span class="comment-note">你的评论正在等待审核。。。</span>
      </c:if>
       <p>${comment.content}</p>
     </div>
     <c:if test="${comment.children!=null&&fn:length(comment.children)!=0}">
       <c:set var="depth" value="${depth+1}" scope="request" />
       <c:set var="parent" value="${status.index%2==0}" scope="request" />
       <c:set var="comments" value="${comment.children}" scope="request" />
       <jsp:include page="comments_list.jsp" flush="false" />
       <c:set var="depth" value="${depth-1}" scope="request" />
     </c:if>
   </li>
  </c:forEach>
</ol>

src/main/webapp/WEB-INF/jsp/common/content.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/tld/shiro-function.tld" prefix="sf" %>
<c:if test="${post.type=='post'}">
<div id="bread_crumb">
  <ul class="clearfix">
   <li><a title="首页" href="${g.domain}">首页</a></li>
   <li><a href="${g.domain}/categorys/${post.category.name}">${post.category.name}</a></li>
   <li class="last">${post.title}</li>
  </ul>
</div>
</c:if>
<div class="post_wrap clearfix">
  <div class="post">
   <h3 class="title"><span>${post.title}</span></h3>
   <div class="post_content">
     <c:choose>
       <c:when test="${!sf:isUser()&&post.pstatus=='secret'}">由于作者设置了权限，你没法阅读此文，请与作者联系</c:when>
       <c:otherwise>
         ${post.content}
         <div style="margin-top: 15px; font-style: italic;">
           <p style="margin:0;"><strong>原创文章，转载请注明：</strong>转载自<a href="${g.domain}">${g.title} – zhouhaocheng.com</a></p>
         </div>
       </c:otherwise>
     </c:choose>
   </div>
  </div>
  <div class="meta">
    <ul>
     <li class="post_date clearfix">
       <span class="date"><fmt:formatDate value="${post.createTime}" pattern="dd" /></span>
       <span class="month"><fmt:formatDate value="${post.createTime}" pattern="MMM"/></span>
       <span class="year"><fmt:formatDate value="${post.createTime}" pattern="yyyy" /></span>
     </li>
     <li class="post_read">${post.rcount}人阅读</li>
     <c:if test="${post.type=='post'}">
       <li class="post_category"><a href="${g.domain}/categorys/${post.category.name}">${post.category.name}</a></li>
     </c:if>
     <li class="post_author">
       <a title="由${post.user.nickName}发布" href="#">${post.user.nickName}</a>
     </li>
     <li class="post_comment">
       <a title="${post.title}" href="#respond">发表评论</a>
     </li>
    </ul>
  </div>
</div>

src/main/webapp/WEB-INF/jsp/common/footer.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<div id="footer" class="clearfix">
  <p id="copyright">
    <span class="copyright">版权所有 ©&nbsp;${g.year}&nbsp;<a href="${g.domain}">${g.title}</a></span>
    <span class="icp">鄂ICP备12046809号</span>
  </p>
  <a id="return_top" href="#">Return Top</a>
</div>
<script src="${g.domain}/resource/js/jscript.js"></script>

src/main/webapp/WEB-INF/jsp/common/head.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="${g.description}" />
<meta name="keywords" content="${g.keywords}" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<title>${ptitle}${ptitle!=null?' | ':''}${g.title}</title>
<link rel="icon" href="${g.domain}/resource/img/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="${g.domain}/resource/css/style.css">
<link rel="stylesheet" media="screen and (max-width:770px)" href="${g.domain}/resource/css/responsive.css">
<script type="text/javascript" src="${g.domain}/resource/js/jquery-1.9.1.min.js"></script>
<!--[if IE 6]>
<script type="text/javascript" src="${g.domain}/resource/js/ie6.js"></script>
<![endif]-->
<link rel="alternate" type="application/rss+xml" href="${g.domain}/feed" title="${g.title}" />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="${g.domain}/xmlrpc/rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="${g.domain}/xmlrpc/wlwmanifest" />