src/main/java/com/zblog/core/dal/entity/Upload.java
package com.zblog.core.dal.entity;

/**
 * 文章、页面的元数据,如文章包含的图片等待
 * 
 * @author zhou
 * 
 */
public class Upload extends BaseEntity{
  /* 对应文章id */
  private String postid;
  /* 图片名称 */
  private String name;
  /* 图片访问路径 */
  private String path;

  public String getPostid(){
    return postid;
  }

  public void setPostid(String postid){
    this.postid = postid;
  }

  public String getName(){
    return name;
  }

  public void setName(String name){
    this.name = name;
  }

  public String getPath(){
    return path;
  }

  public void setPath(String path){
    this.path = path;
  }

}

src/main/java/com/zblog/service/vo/Global.java
package com.zblog.service.vo;

import java.util.Calendar;
import java.util.Date;

import com.zblog.core.dal.constants.OptionConstants;
import com.zblog.core.plugin.ApplicationContextUtil;
import com.zblog.service.OptionsService;

/**
 * view中使用的的对象
 * 
 * @author zhou
 *
 */
public class Global{
  private String domain;

  public Global(String domain){
    this.domain = domain;
  }

  public String getTitle(){
    return getOptionValue(OptionConstants.TITLE);
  }

  public String getSubtitle(){
    return getOptionValue(OptionConstants.SUBTITLE);
  }

  public String getDescription(){
    return getOptionValue(OptionConstants.DESCRIPTION);
  }
  
  public String getKeywords(){
    return getOptionValue(OptionConstants.KEYWORDS);
  }

  public boolean isAllowComment(){
    return Boolean.parseBoolean(getOptionValue(OptionConstants.ALLOW_COMMENT));
  }

  public int getYear(){
    Calendar calendar = Calendar.getInstance();
    calendar.setTime(new Date());
    return calendar.get(Calendar.YEAR);
  }

  public String getDomain(){
    return domain;
  }

  private static String getOptionValue(String name){
    OptionsService optionsService = ApplicationContextUtil.getBean(OptionsService.class);
    return optionsService.getOptionValue(name);
  }

}

src/main/java/com/zblog/web/backend/controller/BackendController.java
package com.zblog.web.backend.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authz.annotation.Logical;
import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.zblog.biz.CommentManager;
import com.zblog.biz.PostManager;
import com.zblog.core.Constants;
import com.zblog.core.dal.constants.PostConstants;
import com.zblog.core.dal.entity.User;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.util.CookieUtil;
import com.zblog.core.util.ServletUtils;
import com.zblog.core.util.StringUtils;
import com.zblog.service.CommentService;
import com.zblog.service.PostService;
import com.zblog.service.UploadService;
import com.zblog.service.UserService;
import com.zblog.service.shiro.StatelessToken;
import com.zblog.service.vo.OSInfo;
import com.zblog.web.backend.form.LoginForm;
import com.zblog.web.backend.form.validator.LoginFormValidator;
import com.zblog.web.support.CookieRemberManager;
import com.zblog.web.support.WebContextFactory;

@Controller
@RequestMapping("/backend")
public class BackendController{
  @Autowired
  private UserService userService;
  @Autowired
  private PostManager postManager;
  @Autowired
  private CommentManager commentManager;
  @Autowired
  private PostService postService;
  @Autowired
  private CommentService commentService;
  @Autowired
  private UploadService uploadService;

  @RequiresRoles(value = { "admin", "editor" }, logical = Logical.OR)
  @RequestMapping(value = "/index", method = RequestMethod.GET)
  public String index(Model model){
    model.addAttribute("osInfo", OSInfo.getCurrentOSInfo());

    /* 基本站点统计信息 */
    model.addAttribute("userCount", userService.count());
    model.addAttribute("postCount", postService.count());
    model.addAttribute("commentCount", commentService.count());
    model.addAttribute("uploadCount", uploadService.count());

    model.addAttribute("posts", postManager.listRecent(10, PostConstants.POST_CREATOR_ALL));
    model.addAttribute("comments", commentManager.listRecent());
    return "backend/index";
  }

  @RequestMapping(value = "/login", method = RequestMethod.GET)
  public String login(String msg, Model model){
    if(WebContextFactory.get().isLogon())
      return "redirect:/backend/index";

    if("logout".equals(msg)){
      model.addAttribute("msg", "您已登出。");
    }else if("unauthenticated".equals(msg)){
      model.addAttribute("msg", "你没有当前操作权限");
    }
    return "backend/login";
  }

  @RequestMapping(value = "/logout")
  public String logout(HttpServletRequest request, HttpServletResponse response){
    CookieRemberManager.logout(request, response);
    SecurityUtils.getSubject().logout();
    CookieUtil cookieUtil = new CookieUtil(request, response);
    cookieUtil.removeCokie(Constants.COOKIE_CSRF_TOKEN);
    cookieUtil.removeCokie("comment_author");
    cookieUtil.removeCokie("comment_author_email");
    cookieUtil.removeCokie("comment_author_url");
    
    return "redirect:/backend/login?msg=logout";
  }

  @RequestMapping(value = "/login", method = RequestMethod.POST)
  public String dashboard(LoginForm form, HttpServletRequest request, HttpServletResponse response){
    MapContainer result = LoginFormValidator.validateLogin(form);
    if(!result.isEmpty()){
      request.setAttribute("msg", result.get("msg"));
      return "backend/login";
    }

    User user = userService.login(form.getUsername(), form.getPassword());
    if(user == null){
      request.setAttribute("msg", "用户名密码错误");
      return "backend/login";
    }

    SecurityUtils.getSubject().login(new StatelessToken(user.getId(), user.getPassword()));
    CookieUtil cookieUtil = new CookieUtil(request, response);
    /* 根据RFC-2109中的规定，在Cookie中只能包含ASCII的编码 */
    cookieUtil.setCookie(Constants.COOKIE_USER_NAME, form.getUsername(), false, 7 * 24 * 3600);
    cookieUtil.setCookie("comment_author", user.getNickName(), "/", false, 365 * 24 * 3600);
    cookieUtil.setCookie("comment_author_email", user.getEmail(), "/", false, 365 * 24 * 3600, false);
    cookieUtil.setCookie("comment_author_url", ServletUtils.getDomain(request), "/", false, 365 * 24 * 3600, false);

    CookieRemberManager.loginSuccess(request, response, user.getId(), user.getPassword(), form.isRemeber());

    return "redirect:" + StringUtils.emptyDefault(form.getRedirectURL(), "/backend/index");
  }

}

src/main/java/com/zblog/web/backend/controller/CategoryController.java
package com.zblog.web.backend.controller;

import java.util.Date;
import java.util.List;

import org.apache.shiro.authz.annotation.Logical;
import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zblog.biz.CategoryManager;
import com.zblog.core.dal.entity.Category;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.util.CollectionUtils;
import com.zblog.core.util.IdGenerator;
import com.zblog.service.CategoryService;
import com.zblog.web.backend.form.validator.CategoryFormValidator;

@Controller("adminCategoryController")
@RequestMapping("/backend/categorys")
@RequiresRoles(value = { "admin", "editor" }, logical = Logical.OR)
public class CategoryController{
  @Autowired
  private CategoryService categoryService;
  @Autowired
  private CategoryManager categoryManager;

  @RequestMapping(method = RequestMethod.GET)
  public String index(){
    return "backend/post/category";
  }

  @ResponseBody
  @RequestMapping(value = "/index", method = RequestMethod.GET)
  public Object data(){
    List<MapContainer> list = categoryManager.listAsTree();
    for(MapContainer temp : list){
      temp.put("text", temp.remove("name"));
      List<MapContainer> nodes = temp.get("nodes");
      if(CollectionUtils.isEmpty(nodes))
        continue;

      for(MapContainer child : nodes){
        child.put("text", child.remove("name"));
        child.put("icon", "glyphicon glyphicon-star");
      }
    }

    return list;
  }

  @ResponseBody
  @RequestMapping(method = RequestMethod.POST)
  public Object insert(Category category, String parent){
    MapContainer form = CategoryFormValidator.validateInsert(category);
    if(!form.isEmpty()){
      return form.put("success", false);
    }

    category.setId(IdGenerator.uuid19());
    category.setCreateTime(new Date());
    category.setLastUpdate(category.getCreateTime());
    return new MapContainer("success", categoryService.insertChildren(category, parent));
  }

  @ResponseBody
  @RequestMapping(value = "/{categoryName}", method = RequestMethod.DELETE)
  public Object remove(@PathVariable String categoryName){
    categoryManager.remove(categoryName);
    return new MapContainer("success", true);
  }

}

src/main/java/com/zblog/web/backend/controller/CommentController.java
package com.zblog.web.backend.controller;

import java.util.Arrays;
import java.util.Collection;

import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zblog.biz.CommentManager;
import com.zblog.core.dal.constants.CommentConstants;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.plugin.PageModel;
import com.zblog.service.CommentService;

@Controller("adminCommentController")
@RequestMapping("/backend/comments")
@RequiresRoles("admin")
public class CommentController{
  @Autowired
  private CommentService commentService;
  @Autowired
  private CommentManager commentManager;

  @RequestMapping(method = RequestMethod.GET)
  public String index(@RequestParam(value = "page", defaultValue = "1") int page,
      @RequestParam(value = "type", defaultValue = "all") String type, Model model){
    Collection<String> status = "all".equals(type) ? Arrays.asList(CommentConstants.TYPE_APPROVE,
        CommentConstants.TYPE_WAIT) : Arrays.asList(type);
    PageModel<MapContainer> pageModel = commentService.listByStatus(page, 15, status);
    model.addAttribute("page", pageModel);
    model.addAttribute("type", type);
    model.addAttribute("stat", commentService.listCountByGroupStatus());
    return "backend/comment/list";
  }

  @ResponseBody
  @RequestMapping(value = "/{commentid}", method = RequestMethod.DELETE)
  public Object remove(@PathVariable("commentid") String commentid){
    commentManager.deleteComment(commentid);
    return new MapContainer("success", true);
  }

  /**
   * 修改评论状态
   * 
   * @param commentid
   * @param status
   * @return
   */
  @ResponseBody
  @RequestMapping(value = "/{commentid}", method = RequestMethod.PUT)
  public Object approve(@PathVariable("commentid") String commentid, String status){
    commentManager.setStatus(commentid, status);
    return new MapContainer("success", true);
  }

}

src/main/java/com/zblog/web/backend/controller/LinkController.java
package com.zblog.web.backend.controller;

import java.util.Date;

import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zblog.core.dal.entity.Link;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.util.IdGenerator;
import com.zblog.core.util.StringUtils;
import com.zblog.service.LinkService;
import com.zblog.web.backend.form.validator.LinkFormValidator;
import com.zblog.web.support.WebContextFactory;

@Controller
@RequestMapping("/backend/links")
@RequiresRoles("admin")
public class LinkController{
  @Autowired
  private LinkService linkService;

  @RequestMapping(method = RequestMethod.GET)
  public String index(@RequestParam(value = "page", defaultValue = "1") int page, Model model){
    model.addAttribute("page", linkService.list(page, 15));
    return "backend/link/list";
  }

  @RequestMapping(method = RequestMethod.POST)
  public String insert(Link link, Model model){
    MapContainer form = LinkFormValidator.validateInsert(link);
    if(!form.isEmpty()){
      model.addAllAttributes(form);
      return "backend/link/edit";
    }

    link.setCreateTime(new Date());
    link.setLastUpdate(link.getCreateTime());
    link.setCreator(WebContextFactory.get().getUser().getNickName());
    link.setId(IdGenerator.uuid19());
    link.setVisible(true);
    linkService.insert(link);
    return "redirect:/backend/links";
  }

  @RequestMapping(method = RequestMethod.PUT)
  public String update(Link link, Model model){
    MapContainer form = LinkFormValidator.validateUpdate(link);
    if(!form.isEmpty()){
      model.addAttribute("link", link);
      model.addAttribute("msg", form.get("msg"));
      return "backend/link/edit";
    }

    link.setLastUpdate(new Date());
    linkService.update(link);
    return "redirect:/backend/links";
  }

  @ResponseBody
  @RequestMapping(value = "/{linkid}", method = RequestMethod.DELETE)
  public Object remove(@PathVariable("linkid") String linkid){
    linkService.deleteById(linkid);
    return new MapContainer("success", true);
  }

  @RequestMapping(value = "/edit", method = RequestMethod.GET)
  public String edit(String lid, Model model){
    if(!StringUtils.isBlank(lid))
      model.addAttribute("link", linkService.loadById(lid));

    return "backend/link/edit";
  }

}

src/main/java/com/zblog/web/backend/controller/OptionsController.java
package com.zblog.web.backend.controller;

import org.apache.shiro.authz.annotation.RequiresRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.zblog.biz.OptionManager;
import com.zblog.core.plugin.MapContainer;
import com.zblog.core.util.CollectionUtils;
import com.zblog.service.CategoryService;
import com.zblog.service.email.MailSenderService;
import com.zblog.web.backend.form.GeneralOption;
import com.zblog.web.backend.form.MailOption;
import com.zblog.web.backend.form.PostOption;
import com.zblog.web.backend.form.validator.MailFormValidator;
import com.zblog.web.backend.form.validator.OptionFormValidator;

@Controller
@RequestMapping("/backend/options")
@RequiresRoles("admin")
public class OptionsController{
  @Autowired
  private CategoryService categoryService;
  @Autowired
  private OptionManager optionManager;
  @Autowired
  private MailSenderService mailSenderService;

  @RequestMapping(value = "/general", method = RequestMethod.GET)
  public String general(Model model){
    model.addAttribute("form", optionManager.getGeneralOption());
    return "backend/options/general";
  }

  @RequestMapping(value = "/general", method = RequestMethod.POST)
  public String updateGeneral(GeneralOption form, Model model){
    model.addAttribute("form", form);
    MapContainer result = OptionFormValidator.validateGeneral(form);
    if(!result.isEmpty()){
      model.addAllAttributes(result);
      return "backend/options/general";
    }

    optionManager.updateGeneralOption(form);
    model.addAttribute("success", true);
    return "backend/options/general";
  }

  @RequestMapping(value = "/post", method = RequestMethod.GET)
  public String post(Model model){
    model.addAttribute("categorys", categoryService.list());
    model.addAttribute("form", optionManager.getPostOption());

    return "backend/options/post";
  }

  @RequestMapping(value = "/post", method = RequestMethod.POST)
  public String updatePost(PostOption form, Model model){
    model.addAttribute("categorys", categoryService.list());
    model.addAttribute("form", form);

    MapContainer result = OptionFormValidator.validatePost(form);
    if(!result.isEmpty()){
      model.addAllAttributes(result);
      return "backend/options/post";
    }

    model.addAttribute("success", true);
    optionManager.updatePostOption(form);
    return "backend/options/post";
  }

  @RequestMapping(value = "/email", method = RequestMethod.GET)
  public String mail(Model model){
    model.addAttribute("form", optionManager.getMailOption());
    return "backend/options/email";
  }

  @RequestMapping(value = "/email", method = RequestMethod.POST)
  public String updateMail(MailOption form, Model model){
    MapContainer result = MailFormValidator.validate(form);
    if(!CollectionUtils.isEmpty(result)){
      model.addAllAttributes(result);
      return "backend/options/email";
    }

    optionManager.updateMailOption(form);
    mailSenderService.setServerInfo(form);
    return "backend/options/email";
  }

}

src/main/webapp/WEB-INF/jsp/backend/upload/edit.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<!DOCTYPE Html>
<html>
 <head>
  <jsp:include page="../common/bootstrap.jsp" flush="false" />
  <link rel="stylesheet" href="${g.domain}/resource/webuploader-0.1.5/webuploader.css" />
 </head>
 <body style="margin-top: 50px;">
  <jsp:include page="../common/navbar.jsp" flush="false" />
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2" id="sidebar" style="padding: 0;">
        <jsp:include page="../common/sidebar.jsp" flush="false" />
      </div>
      <div class="col-sm-9 col-md-10">
        <ol class="breadcrumb header">
          <li><span class="icon glyphicon glyphicon-home"></span>主菜单</li>
          <li>多媒体</li>
          <li class="active">上传附件</li>
        </ol>
         <div class="panel panel-default">
           <div class="panel-heading"><span class="icon icon-upload-alt icon-large"></span>内容</div>
           <div class="panel-body">
             <div id="uploader">
               <div class="upload-list">
                 <div class="placeholder">
                   <div id="picker"></div>
                   <p>或将文件拖到这里，单次最多可选300个</p>
                 </div>
               </div>
               <div class="tip">最大上传文件大小：2MB.</div>
               <div id="status-bar" style="display: none;">
                <div class="info"></div>
                <div class="btns">
                  <div id="append-picker"></div>
                  <div class="uploadBtn" onclick="zblog.upload.upload();">开始上传</div>
                </div>
               </div>
             </div>
           </div>
          </div>

      </div>
    </div>
  </div>
  <script type="text/javascript" src="${g.domain}/resource/webuploader-0.1.5/webuploader.min.js"></script>
  <script type="text/javascript" src="${g.domain}/resource/js/backend/upload.js"></script>
 </body>
</html>

src/main/webapp/WEB-INF/jsp/backend/upload/list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="z" uri="/WEB-INF/tld/function.tld" %>
<!DOCTYPE Html>
<html>
 <head>
  <jsp:include page="../common/bootstrap.jsp" flush="false" />
 </head>
 <body style="margin-top: 50px;">
  <jsp:include page="../common/navbar.jsp" flush="false" />
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2" id="sidebar" style="padding: 0;">
        <jsp:include page="../common/sidebar.jsp" flush="false" />
      </div>
      <div class="col-sm-9 col-md-10">
        <ol class="breadcrumb header">
          <li><span class="icon glyphicon glyphicon-home"></span>主菜单</li>
          <li class="active">多媒体</li>
        </ol>
        <div class="panel panel-default">
          <div class="panel-heading"><span class="icon glyphicon glyphicon-list"></span>媒体库</div>
          <div class="panel-body">
           <table id="upload-table" class="table table-striped list-table">
               <thead><tr>
                 <th style="width: 80px;">文件</th>
                 <th style="width: 30%"></th>
                 <th>作者</th>
                 <th>上传至</th>
                 <th>日期</th>
                 <th class="center">操作</th>
               </tr></thead>
              <tbody>
               <c:forEach items="${page.content}" var="upload">
                 <tr><td><img src="${upload.path}" width="80" height="50" /></td>
                     <td class="filename"><strong>${upload.name}</strong><p class="fileformat">${z:fileExt(upload.name)}</p>
                        <div class="row-action">
                          <span><a href="javascript:zblog.upload.remove('${upload.id}');">永久删除</a>&nbsp;|&nbsp;</span>
                          <span><a href="#">查看</a></span>
                        </div></td>
                     <td>${upload.user.nickName}</td><td><a href='${g.domain}/posts/${upload.post.id}' target="_blank">${upload.post.title}</a></td>
                     <td><fmt:formatDate value="${upload.createTime}" pattern="yyyy-MM-dd"/></td>
                     <td class="center">
                       <span class="glyphicon glyphicon-trash pointer" onclick="zblog.upload.remove('${upload.id}');"></span></td></tr>
               </c:forEach>
              </tbody>
            </table>
            <div class="row-fulid">
              <div class="col-sm-6 col-md-6">
                <div class="page-info">第 ${page.pageIndex}页, 共 ${page.totalPage}页, ${page.totalCount} 项</div>
              </div>
              <div class="col-sm-6 col-md-6">
                <div id="pager">
                  <jsp:include page="../common/pagination.jsp" flush="false" />
              </div>
            </div>
          </div>
         </div>
       </div>

      </div>
    </div>
  </div>
  <script type="text/javascript" src="${g.domain}/resource/js/backend/admin.upload.js"></script>
 </body>
</html>